# Generated by Django 4.1 on 2022-08-22 21:53

from django.db import migrations, models


# def create_service(apps, schema_editor):
#     Service = apps.get_model('services', 'Service')
#     Service.objects.create(
#         name='سرویس نامه رسان',
#         price=10000
#     )
#     Service.objects.create(
#         name='سرویس سوخت رسان',
#         price=20000
#     )
#     Service.objects.create(
#         name='سرویس امداد رسان',
#         price=30000
#     )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        # run a python script after migration
        # migrations.RunPython(create_service, migrations.RunPython.noop),
    ]
