# Generated by Django 4.1 on 2022-08-23 06:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('created', 'ایجاد شده'), ('reviewed', 'بررسی شده'), ('finalized', 'نهایی شده'), ('canceled', 'نقص شده')], db_index=True, default='created', max_length=10, verbose_name='state')),
                ('user_extra_description', models.TextField(blank=True, null=True)),
                ('staff_extra_description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('service_price', models.PositiveBigIntegerField(blank=True, help_text='این فیلد در لحظه ی تایید شدن درخواست، به صورت اتوماتیک ذخیره میشود', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Service',
                'verbose_name_plural': 'Request Services',
            },
        ),
    ]
