# Generated by Django 4.1 on 2022-08-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_requestservice_fee_for_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestservice',
            name='fee_for_user',
        ),
        migrations.AddField(
            model_name='requestservice',
            name='confirmed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='requestservice',
            name='fee',
            field=models.PositiveIntegerField(blank=True, help_text='این فیلد در لحظه ی تایید شدن درخواست، به صورت اتوماتیک ذخیره میشود تا در صورت تغییر درصد کارمزد و یا تغییر نوع عضویت کاربر، درخواست های ثبت شده تغییر قیمت نداشته باشند.', null=True),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='state',
            field=models.CharField(choices=[('created', 'ایجاد شده'), ('confirmed', 'بررسی شده'), ('finalized', 'نهایی شده'), ('canceled', 'نقص شده')], db_index=True, default='created', max_length=10, verbose_name='state'),
        ),
    ]
