# Generated by Django 4.1 on 2022-08-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_requestservice_fee_for_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestservice',
            old_name='is_verified',
            new_name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='services.service'),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='state',
            field=models.CharField(choices=[('created', 'ایجاد شده'), ('confirmed', 'بررسی شده'), ('finalized', 'نهایی شده'), ('canceled', 'نقص شده')], db_index=True, default='created', max_length=9, verbose_name='state'),
        ),
    ]
